const actions = {
  profile: {
    DATA_FETCHING: "USER_DATA_FETCHING",
    DATA_FETCHED: "USER_DATA_FETCHED",
    DATA_FETCH_ERROR: "USER_DATA_FETCH_ERROR",
    USER_DATA_EDITED: "USER_USER_DATA_EDITED",
    IMAGE_UPDATED: "USER_IMAGE_UPDATED",
  },
  post: {
    DATA_FETCHING: "USER_DATA_FETCHING",
    DATA_FETCHED: "USER_DATA_FETCHED",
    DATA_FETCH_ERROR: "USER_DATA_FETCH_ERROR",
    DATA_CREATED: "USER_DATA_CREATED",
    DATA_DELETED: "USER_DATA_DELETED",
    DATA_EDITED: "USER_DATA_EDITED",
  },
};

export { actions };

